modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="modern_items_mod"
version="1.0.0"
displayName="Modern items mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="jacob, MCreator"

[[dependencies.modern_items_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



